### ISSUE TITLE
Daily Songs with Firestore

### ISSUE THREAD

**Issue by bruh345180** [eggsy/website#12]
How to create firestore database for daily songs?

**Comment by eggsy** [comment]
Do you _actually_ need it? Website can work without a Firebase connection if you just remove some parts.

**Comment by bruh345180** [comment]
> Do you _actually_ need it? Website can work without a Firebase connection if you just remove some parts.

Yes because i want to use this feature.

**Comment by eggsy** [comment]
You'll need to maintain it though, it'll be a workload to you. You'll have to create a database, add documents with a custom tool (I have a terminal tool that allows me to add songs to Firestore)... It takes time. You'll also have to get a YouTube API key, a KSoft.si API access and of course, a Firebase account.

I can help you with setting a Firebase account and connecting it, but you'll have to figure out your own way to add documents and fetch song info/lyrics...

I highly recommend not dealing with this, if you have a REST API, you can even use there if you want.

**Comment by bruh345180** [comment]
Thanks for reply you're right. Issue Closed
