### ISSUE TITLE
Nuxt Fatal Error: You are missing Firebase options, please check your .env file and make sure all required keys are present.

### ISSUE THREAD

**Issue by talhabw** [eggsy/website#19]
First, I cloned the repo
and run command: `yarn`
then run command: `yarn dev`

as a result I'm getting this error: 
```
Nuxt Fatal Error 

Error: You are missing Firebase options, please check your .env file and make sure all required keys are present.
```

I don't want to use firebase btw. I just want a static website.

**Comment by eggsy** [comment]
Just remove `config/modules/firebase.ts` and references of it in `config/modules.ts` as well as other references in Vue files, I don't really have a guide on that but removing these two would make it compile and then you can run the app without issues.

**Comment by talhabw** [comment]
I removed 
`config/modules/firebase.ts `
and references in 
`config/modules.ts` and `config/plugins.ts`.

This fixed the problem.

Thanks.
