### ISSUE TITLE
A website bug 

### ISSUE THREAD

**Issue by Avyansh0001** [eggsy/website#33]
As per my understanding, can you please replace the **dot** represented before the status as right now when I'm seeing the website, it shows a Red dot and says **online**... 

![image](https://user-images.githubusercontent.com/75159744/159158750-6a267672-6f8e-4aa4-9307-af3976c2e5ab.png)

P.S. Green Dot should represent **Online**
       Red Dot should represent **Do Not Disturb**
       Grey Dot should represent **Offline**
       Yellow dot should represent **Idle**
       
     
   I hope you read my request
   Thanks and Regards
   [**Avyansh**](https://avyanshralph.xyz)

**Comment by eggsy** [comment]
I understand what you mean but the idea of putting red there is for the people **_who know it is related to Discord_**. There are people that visit my website and see "a red dot" and an "online" text let's say. They think it's cool. But, if I were to put "Do Not Disturb" there, that would make no sense, for someone who doesn't know I am on Discord, or that is related to Discord. It would be like, "what? I am disturbing him just by visiting his website?", that's the point why I don't want to put nothing more than just "Online" and the colors for people **who know what it means**. As for the Grey dot, it does say I am offline. But for the others, I like the idea of keeping it "Online".

**Comment by Avyansh0001** [comment]
Oh ok, that's great

Thanks
